context.properties = {
  core.name = audiofire-ffado-host
  default.clock.rate = 48000
  default.clock.allowed-rates = [ 48000 ]
  default.clock.quantum = 256
  default.clock.min-quantum = 256
  default.clock.max-quantum = 256
}

context.modules = [
  {
    name = libpipewire-module-ffado-driver
    args = {
      remote.name = pipewire-0
      node.group = audiofire-ffado-group
      driver.mode = duplex
      ffado.devices = [ "guid:0x0014866faf73b593" ]
      ffado.period-size = 256
      ffado.period-num = 2
      ffado.sample-rate = 48000
      ffado.verbose = 3
      ffado.realtime = true
      ffado.rtprio = 88
      sink.props = {
        node.name = audiofire_ffado_output
        node.description = "AudioFire4 FFADO Output"
        node.autoconnect = false
        node.dont-reconnect = true
        node.pause-on-idle = true
        port.physical = false
        priority.driver = 10
        priority.session = 1
        session.suspend-timeout-seconds = 0
      }
      source.props = {
        node.name = audiofire_ffado_input
        node.description = "AudioFire4 FFADO Input"
        node.autoconnect = false
        node.dont-reconnect = true
        node.pause-on-idle = true
        port.physical = false
        priority.driver = 11
        priority.session = 1
        session.suspend-timeout-seconds = 0
      }
    }
    flags = [ ifexists nofail ]
  }
]
