context.properties = {
  default.clock.rate = 48000
  default.clock.allowed-rates = [ 48000 ]
  default.clock.quantum = 256
  default.clock.min-quantum = 256
  default.clock.max-quantum = 256
}

context.modules = [
  {
    name = libpipewire-module-ffado-driver
    args = {
      remote.name = internal
      node.group = saffire-ffado-group
      driver.mode = duplex
      ffado.devices = [ "guid:0x00130e0401c04de0" ]
      ffado.period-size = 256
      ffado.period-num = 2
      ffado.sample-rate = 48000
      ffado.verbose = 3
      ffado.realtime = true
      ffado.rtprio = 93
      sink.props = {
        node.name = saffire_ffado_output
        node.description = "Saffire Pro 24 FFADO Output"
        priority.driver = 4001
        priority.session = 4000
        session.suspend-timeout-seconds = 0
      }
      source.props = {
        node.name = saffire_ffado_input
        node.description = "Saffire Pro 24 FFADO Input"
        priority.driver = 4000
        priority.session = 200
        session.suspend-timeout-seconds = 0
      }
    }
    flags = [ ifexists nofail ]
  }
]
