context.objects = [
    {   factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "System Sounds"
           node.description = "System Sounds"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [ FL FR ]
           monitor.channel-volumes = true
           priority.session = 2000
        }
    }
    {   factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "Games"
           node.description = "Games"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [ FL FR ]
           monitor.channel-volumes = true
        }
    }
    {   factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "Music"
           node.description = "Music"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [ FL FR ]
           monitor.channel-volumes = true
        }
    }
]
