context.modules = [
  {
    name = libpipewire-module-ffado-driver
    args = {
      driver.mode = sink
      ffado.devices = [ "hw:0" ]
      ffado.period-size = 1024
      ffado.period-num = 3
      ffado.sample-rate = 48000
      ffado.realtime = true
      ffado.rtprio = 88
      sink.props = {
        node.name = "audiofire_ffado_output"
        node.description = "AudioFire4 FFADO Output"
        priority.driver = 10
        priority.session = 10
      }
      source.props = {
        node.name = "audiofire_ffado_input"
        node.description = "AudioFire4 FFADO Input"
        priority.driver = 10
        priority.session = 10
      }
    }
    flags = [ ifexists nofail ]
  }
]
