context.modules = [
  {
    name = libpipewire-module-ffado-driver
    args = {
      driver.mode = duplex
      ffado.devices = [ "hw:0" ]
      ffado.period-size = 512
      ffado.period-num = 3
      ffado.sample-rate = 48000
      ffado.verbose = 6
      ffado.realtime = true
      ffado.rtprio = 93
      sink.props = {
        node.name = "saffire_ffado_output"
        node.description = "Saffire Pro 24 FFADO Output"
        priority.driver = 4000
        priority.session = 4000
      }
      source.props = {
        node.name = "saffire_ffado_input"
        node.description = "Saffire Pro 24 FFADO Input"
        priority.driver = 200
        priority.session = 200
      }
    }
    flags = [ ifexists nofail ]
  }
]
