stream.rules = [
  {
    matches = [
      {
        application.name = "BattleTech"
        media.class = "Stream/Output/Audio"
      }
      {
        node.name = "BattleTech"
        media.class = "Stream/Output/Audio"
      }
      {
        application.process.binary = "BattleTech"
        media.class = "Stream/Output/Audio"
      }
    ]
    actions = {
      update-props = {
        target.object = "Games"
        node.dont-move = true
        state.restore-target = false
      }
    }
  }
]
