# WirePlumber Configuration for Default Virtual Sink

default-policy {
    move = true
    follow = true
}

monitor.alsa.rules = [
    {
        matches = [
            { node.name = "System Sounds" }
        ]
        actions = {
            update-props = {
                device.disabled = false
            }
        }
    }
]
