wireplumber.components = [
  {
    name = "firefox-to-ardour.lua", type = script/lua
    provides = custom.firefox-to-ardour
  }
]

wireplumber.profiles = {
  main = {
    custom.firefox-to-ardour = required
  }
}
