wireplumber.components = [
  {
    name = "route-to-ardour.lua", type = script/lua
    provides = custom.route-to-ardour
  }
]

wireplumber.profiles = {
  main = {
    custom.route-to-ardour = required
  }
}
