wireplumber.components = [
  {
    name = "route-midi-to-spotify.lua", type = script/lua
    provides = custom.route-midi-to-spotify
  }
]

wireplumber.profiles = {
  main = {
    custom.route-midi-to-spotify = required
  }
}
