monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.firewire-0x00130e0401c04de0.multichannel-output"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 3000
        priority.session = 3000
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_input.firewire-0x00130e0401c04de0.multichannel-input"
      }
      {
        node.name = "alsa_input.usb-HD_Web_Camera_HD_Web_Camera_Ucamera001-02.mono-fallback"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 100
      }
    }
  }
]
