name = "pwppp"
version = "1.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea9d8c9ca344c85786b3bd3f5a35fa153fb48d603f89ff903ed02b6d170134a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
