name = "pwppp"
version = "1.1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2b653ca35b23a12e1c10de4cf18785890969e4de0dda4de5b5ded96fd96b2f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
