#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 09 19:31:33 BST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Fantasy_Shaders_v1.0.zip
enableShaders=false
