name = "gigglesomething"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11ff01bad5b0cd902a89f95c8fc37e57c80f3534a49e436f36337900804bc5c2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
