name = "gigglesomething"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5676dd7b64535d5c5da2aaccfa15eebed5b6baf10033c13362fc8e33f4135973"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
