# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  disko.devices = pkgs.callPackage ./disks.nix {
    disks = [ "/dev/nvme0n1" ];
  };
#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/cdc76cbd-265c-4bc7-ad6e-567add5ee18b";
#      fsType = "ext4";
#    };
#
#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/36B2-9B8F";
#      fsType = "vfat";
#    };

#  swapDevices =
#    [ { device = "/dev/disk/by-uuid/c60a74f7-e47a-4a66-b60e-49f3040fd7b5"; }
#    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
